// <auto-generated />
using System;
using DataAccess.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20230930210849_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Concrete.Component", b =>
                {
                    b.Property<Guid>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            ComponentId = new Guid("b65631e9-5a58-4108-8905-65aa08939387"),
                            Code = "F-EN-E23-01",
                            Description = "PASIFIC KAĞIT HAVLU - FASON",
                            IsDeleted = false
                        },
                        new
                        {
                            ComponentId = new Guid("f94d9fca-f2c7-46c9-8a78-e71d532281a3"),
                            Code = "F-EN-E77-02",
                            Description = "35 LT KOVA ÇEMBER",
                            IsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
